// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBst-EgWuwLNQE9mOXqdIvXZjb2sBTiXdQ',
    appId: '1:30458743615:web:6405fb990cc6068025218a',
    messagingSenderId: '30458743615',
    projectId: 'fintech-cecdb',
    authDomain: 'fintech-cecdb.firebaseapp.com',
    storageBucket: 'fintech-cecdb.firebasestorage.app',
    measurementId: 'G-VEYZ0L1KSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByEZB05rEVssPTkXuDWpYBT_NOVXGNspI',
    appId: '1:30458743615:android:957830ad2d814a7425218a',
    messagingSenderId: '30458743615',
    projectId: 'fintech-cecdb',
    storageBucket: 'fintech-cecdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUOBZwxF1RLH83o0O-x2NhC1RncPe25w',
    appId: '1:30458743615:ios:810ed65815bbdad825218a',
    messagingSenderId: '30458743615',
    projectId: 'fintech-cecdb',
    storageBucket: 'fintech-cecdb.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAUOBZwxF1RLH83o0O-x2NhC1RncPe25w',
    appId: '1:30458743615:ios:810ed65815bbdad825218a',
    messagingSenderId: '30458743615',
    projectId: 'fintech-cecdb',
    storageBucket: 'fintech-cecdb.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBst-EgWuwLNQE9mOXqdIvXZjb2sBTiXdQ',
    appId: '1:30458743615:web:8c88138244143e5125218a',
    messagingSenderId: '30458743615',
    projectId: 'fintech-cecdb',
    authDomain: 'fintech-cecdb.firebaseapp.com',
    storageBucket: 'fintech-cecdb.firebasestorage.app',
    measurementId: 'G-5R4M0WWW7V',
  );

}